/**
 * BHARAT — Build the Civilization
 * 10 Core Architectural Structures & Progression Systems
 */

import { BuildingDefinition, BuildingCost, BuildingProductionRate } from '../types/civilization';

export const BUILDINGS_CATALOG: Record<string, BuildingDefinition> = {
  civ_center: {
    id: 'civ_center',
    name: 'Civilization Center',
    sanskritName: 'Raja Sabha',
    category: 'citadel',
    footprint: { width: 2, height: 2 },
    maxLevel: 10,
    description: 'The sovereign heart of your settlement. Directs civic administration, unlocks new building plots, and establishes regional authority.',
    historicalSignificance: 'Ancient Indian municipal citadels (such as those at Harappa, Mohenjo-daro, and Kalibangan) were raised upon massive mud-brick platforms to protect civic administration from catastrophic seasonal floods.',
    archaeologicalSiteRef: 'Harappa Citadel Platform & Kalibangan Upper Citadel',
    requiredCivCenterLevel: (level: number) => 1,
    costForLevel: (level: number): BuildingCost => ({
      wood: 40 * level,
      stone: 35 * level,
      clay: 45 * level,
      knowledge: 15 * level,
    }),
    upgradeTimeSeconds: (level: number) => 10 + level * 15,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'knowledge',
      amountPerHour: 20 * level,
      label: `+${20 * level} Knowledge / hour (Civic Governance)`,
    }),
    storageBonusForLevel: (level: number) => 150 * level,
    populationCapacityBonus: (level: number) => 6 * level,
  },

  granary: {
    id: 'granary',
    name: 'Granary',
    sanskritName: 'Koshagara',
    category: 'storage',
    footprint: { width: 1, height: 1 },
    maxLevel: 8,
    description: 'Elevated timber and brick storehouse designed with natural air ducts to preserve grain stocks against heat, moisture, and pests.',
    historicalSignificance: 'Great granaries discovered across the Indus-Saraswati basin featured raised wooden sleepers and under-floor ventilation slots, ensuring seed grains could survive extended droughts and monsoonal mildew.',
    archaeologicalSiteRef: 'The Great Granary of Mohenjo-daro & Harappan Grain Processing Terraces',
    requiredCivCenterLevel: (level: number) => 1,
    costForLevel: (level: number): BuildingCost => ({
      wood: 25 * level,
      clay: 30 * level,
    }),
    upgradeTimeSeconds: (level: number) => 8 + level * 10,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'food',
      amountPerHour: 40 * level,
      label: `+${40 * level} Food / hour (Grain Threshing)`,
    }),
    storageBonusForLevel: (level: number) => 250 * level,
    populationCapacityBonus: (level: number) => 2 * level,
  },

  timber_yard: {
    id: 'timber_yard',
    name: 'Timber Yard',
    sanskritName: 'Darushala',
    category: 'production',
    footprint: { width: 1, height: 1 },
    maxLevel: 8,
    description: 'Saws and cures seasoned Sal, Teak, and Shisham timber harvested from the dense riverine groves for all structural framing.',
    historicalSignificance: 'Subcontinental joiners pioneered mortise-and-tenon interlocking timber frameworks for domestic dwellings and river craft, avoiding perishable iron nails long before classical antiquity.',
    archaeologicalSiteRef: 'Pataliputra Wooden Palisade & Lothal Shipyard Joinery Records',
    requiredCivCenterLevel: (level: number) => 1,
    costForLevel: (level: number): BuildingCost => ({
      wood: 15 * level,
      clay: 15 * level,
    }),
    upgradeTimeSeconds: (level: number) => 6 + level * 8,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'wood',
      amountPerHour: 60 * level,
      label: `+${60 * level} Wood / hour`,
    }),
    storageBonusForLevel: (level: number) => 100 * level,
    populationCapacityBonus: (level: number) => 1,
  },

  stone_yard: {
    id: 'stone_yard',
    name: 'Stone Yard',
    sanskritName: 'Shilpashala',
    category: 'production',
    footprint: { width: 1, height: 1 },
    maxLevel: 8,
    description: 'Extracts and hews heavy granite, basalt, and sandstone blocks for robust civic foundations and stepped defensive ramparts.',
    historicalSignificance: 'Ancient stone quarrying utilized wooden wedges soaked in water to split rock along natural cleavage planes, as seen in the cyclopean masonry of early northern fortification walls.',
    archaeologicalSiteRef: 'Rajgir Cyclopean Walls & Dholavira Dressed Stone Enclosures',
    requiredCivCenterLevel: (level: number) => 1,
    costForLevel: (level: number): BuildingCost => ({
      wood: 25 * level,
      clay: 20 * level,
    }),
    upgradeTimeSeconds: (level: number) => 8 + level * 10,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'stone',
      amountPerHour: 50 * level,
      label: `+${50 * level} Stone / hour`,
    }),
    storageBonusForLevel: (level: number) => 100 * level,
    populationCapacityBonus: (level: number) => 1,
  },

  clay_workshop: {
    id: 'clay_workshop',
    name: 'Clay Workshop',
    sanskritName: 'Kumbhashala',
    category: 'production',
    footprint: { width: 1, height: 1 },
    maxLevel: 8,
    description: 'Mixes fine river silt with chaff, molds standardized bricks in the 1:2:4 ratio, and fires waterproof terracotta in high-heat downdraft kilns.',
    historicalSignificance: 'The strict 1:2:4 ratio (thickness:width:length) of Indus bricks allowed interlocking English bond masonry that resisted earth tremors and water pressure across millennia.',
    archaeologicalSiteRef: 'Kalibangan Brick Kilns & Rakhigarhi Terracotta Workings',
    requiredCivCenterLevel: (level: number) => 1,
    costForLevel: (level: number): BuildingCost => ({
      wood: 20 * level,
      stone: 15 * level,
    }),
    upgradeTimeSeconds: (level: number) => 8 + level * 10,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'clay',
      amountPerHour: 55 * level,
      label: `+${55 * level} Clay / hour`,
    }),
    storageBonusForLevel: (level: number) => 100 * level,
    populationCapacityBonus: (level: number) => 1,
  },

  knowledge_center: {
    id: 'knowledge_center',
    name: 'Knowledge Center',
    sanskritName: 'Gurukula',
    category: 'science',
    footprint: { width: 1, height: 1 },
    maxLevel: 8,
    description: 'An open-air pavilion where scholars, scribes, and astronomers preserve traditions, record monsoon cycles, and advance civil engineering.',
    historicalSignificance: 'Subcontinental centers of learning blended oral mnemonic preservation (Shruti) with empirical astronomy (Sulba Sutras), geometry for hearth alignments, and hydraulic calculations.',
    archaeologicalSiteRef: 'Takshashila & Nalanda Excavations · Sulba Sutra Geometric Treatises',
    requiredCivCenterLevel: (level: number) => 2,
    costForLevel: (level: number): BuildingCost => ({
      wood: 40 * level,
      stone: 35 * level,
      clay: 40 * level,
    }),
    upgradeTimeSeconds: (level: number) => 12 + level * 14,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'knowledge',
      amountPerHour: 45 * level,
      label: `+${45 * level} Knowledge / hour (Scholarly Inquiries)`,
    }),
    storageBonusForLevel: (level: number) => 50 * level,
    populationCapacityBonus: (level: number) => 3 * level,
  },

  training_ground: {
    id: 'training_ground',
    name: 'Training Ground',
    sanskritName: 'Akhada',
    category: 'military',
    footprint: { width: 1, height: 1 },
    maxLevel: 6,
    description: 'Compacted earthen arena where recruits drill with bamboo lances, composite bows, and defensive shields to protect the civilization.',
    historicalSignificance: 'Ancient Indian martial arts (Dhanurveda, Kalaripayattu) emphasized rigorous physical conditioning, archery precision, and coordination with terrain rather than mere brute force.',
    archaeologicalSiteRef: 'Kurushetra Tactical Records & Classical Dhanurveda Manuscripts',
    requiredCivCenterLevel: (level: number) => 2,
    costForLevel: (level: number): BuildingCost => ({
      wood: 35 * level,
      stone: 30 * level,
      clay: 25 * level,
    }),
    upgradeTimeSeconds: (level: number) => 10 + level * 12,
    productionForLevel: (level: number) => null,
    storageBonusForLevel: (level: number) => 50 * level,
    populationCapacityBonus: (level: number) => 5 * level,
  },

  market: {
    id: 'market',
    name: 'Market Square',
    sanskritName: 'Vipani',
    category: 'economy',
    footprint: { width: 1, height: 1 },
    maxLevel: 6,
    description: 'Paved thoroughfare where domestic craftspeople and regional caravans trade grains, timber, carnelian beads, and copper ingots.',
    historicalSignificance: 'Excavations reveal standardized cubical chert weights following binary and decimal progressions (1, 2, 4, 8, 16, 32...) that ensured honest merchant trade across thousands of kilometers.',
    archaeologicalSiteRef: 'Lothal Bead Factory & Harappan Standard Chert Metric Sets',
    requiredCivCenterLevel: (level: number) => 3,
    costForLevel: (level: number): BuildingCost => ({
      wood: 50 * level,
      stone: 40 * level,
      clay: 50 * level,
    }),
    upgradeTimeSeconds: (level: number) => 14 + level * 15,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'food',
      amountPerHour: 30 * level,
      label: `+${30 * level} Food & Trade Logistics / hour`,
    }),
    storageBonusForLevel: (level: number) => 200 * level,
    populationCapacityBonus: (level: number) => 4 * level,
  },

  water_structure: {
    id: 'water_structure',
    name: 'Water Structure',
    sanskritName: 'Jalashaya',
    category: 'water',
    footprint: { width: 1, height: 1 },
    maxLevel: 6,
    description: 'A stone-lined stepped reservoir and silt trap that harnesses monsoon runoff to supply drinking water and nourish adjacent fields.',
    historicalSignificance: 'Dholavira in Kutch featured sixteen monumental rock-cut reservoirs interconnected by channels that could store millions of liters of rainwater, defying the arid desert landscape.',
    archaeologicalSiteRef: 'UNESCO World Heritage: Dholavira Water Harvesting System',
    requiredCivCenterLevel: (level: number) => 2,
    costForLevel: (level: number): BuildingCost => ({
      stone: 45 * level,
      clay: 55 * level,
    }),
    upgradeTimeSeconds: (level: number) => 12 + level * 14,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'food',
      amountPerHour: 50 * level,
      label: `+${50 * level} Food / hour (Irrigation Boost)`,
    }),
    storageBonusForLevel: (level: number) => 150 * level,
    populationCapacityBonus: (level: number) => 8 * level,
  },

  craft_house: {
    id: 'craft_house',
    name: 'Craft House',
    sanskritName: 'Karmashala',
    category: 'production',
    footprint: { width: 1, height: 1 },
    maxLevel: 6,
    description: 'Specialized artisan guild housing micro-drills, copper smelting crucibles, lapidary workshops, and cotton textile looms.',
    historicalSignificance: 'Harappan craftspeople mastered long carnelian beads bleached with white chemical alkaline etchings, traded as prestigious luxury goods as far as Mesopotamia.',
    archaeologicalSiteRef: 'Chanhudaro Artisan Quarters & Lothal Gem Polishing Workshops',
    requiredCivCenterLevel: (level: number) => 3,
    costForLevel: (level: number): BuildingCost => ({
      wood: 45 * level,
      stone: 40 * level,
      clay: 40 * level,
      knowledge: 30 * level,
    }),
    upgradeTimeSeconds: (level: number) => 14 + level * 16,
    productionForLevel: (level: number): BuildingProductionRate => ({
      resource: 'knowledge',
      amountPerHour: 35 * level,
      label: `+${35 * level} Craft Knowledge / hour`,
    }),
    storageBonusForLevel: (level: number) => 150 * level,
    populationCapacityBonus: (level: number) => 3 * level,
  },
};
