/**
 * BHARAT — Build the Civilization
 * Subcontinent Regional Map & Historical Expeditions
 */

import { SubcontinentMapRegion } from '../types/civilization';

export const MAP_REGIONS_CATALOG: SubcontinentMapRegion[] = [
  {
    id: 'saraswati_delta',
    title: 'Saraswati River Confluence',
    sanskritName: 'Saraswati Sangama',
    historicalEra: 'Early Harappan Horizon (c. 3300–2600 BCE)',
    terrainDescription: 'Braided perennial river channels fringed with thick Sal timber groves and alluvial silt flats.',
    archaeologicalSite: 'Kalibangan & Banawali River Horizons',
    historicalInsight: 'Satellite imagery and geological core drillings demonstrate a mighty palaeochannel system supporting dense early agricultural clusters along the Ghaggar-Hakra drainage.',
    recommendedPower: 15,
    scoutDurationSeconds: 15,
    rewards: {
      knowledge: 40,
      wood: 80,
      artifactTitle: 'Incised Fish & Pipal Leaf Pottery Shard',
    },
    status: 'unlocked',
    coordinates: { x: 34, y: 36 },
  },
  {
    id: 'mehrgarh_terrace',
    title: 'Bolan Valley Terraces',
    sanskritName: 'Bolan Upatyaka',
    historicalEra: 'Aceramic & Ceramic Neolithic (c. 7000–4500 BCE)',
    terrainDescription: 'Arid piedmont foothills dissected by seasonal mountain streams and terraced mud-brick homesteads.',
    archaeologicalSite: 'Mehrgarh Excavations (Jarrige Expeditions)',
    historicalInsight: 'Demonstrates continuous technological transition from hunting and wild barley gathering to domesticated zebu cattle, lapis bead drilling, and proto-dentistry.',
    recommendedPower: 25,
    scoutDurationSeconds: 25,
    rewards: {
      knowledge: 60,
      clay: 70,
      artifactTitle: 'Steatite Micro-Bead Necklace & Neolithic Sickle',
    },
    status: 'unlocked',
    coordinates: { x: 20, y: 28 },
  },
  {
    id: 'dholavira_island',
    title: 'Khadir Bet Salt Citadel',
    sanskritName: 'Dholavira Durga',
    historicalEra: 'Mature Harappan Phase (c. 2600–1900 BCE)',
    terrainDescription: 'Isolated seasonal salt marsh island guarded by monumental dressed-stone citadels and deep rock-cut cisterns.',
    archaeologicalSite: 'Dholavira (ASI Excavations under R.S. Bisht)',
    historicalInsight: 'Engineered sixteen massive stone-cut reservoirs and stormwater check-dams capturing ephemeral monsoon torrents, complete with an iconic 10-character signboard.',
    recommendedPower: 45,
    scoutDurationSeconds: 35,
    rewards: {
      knowledge: 80,
      stone: 120,
      artifactTitle: 'Large Crystalline Signboard Gypsum Inlay',
    },
    status: 'locked',
    coordinates: { x: 28, y: 55 },
  },
  {
    id: 'lothal_dock',
    title: 'Gulf of Khambhat Maritime Port',
    sanskritName: 'Lothal Pattan',
    historicalEra: 'Harappan Maritime Trade Era (c. 2400–1900 BCE)',
    terrainDescription: 'Tidal mangrove estuary engineered with a kiln-fired brick basin and sluice gates to berth sea-going dhows.',
    archaeologicalSite: 'Lothal Tidal Dockyard & Warehouse Complex',
    historicalInsight: 'Recognized as the world’s earliest engineered maritime tidal dockyard, connecting subcontinental merchants with Dilmun (Bahrain) and Magan (Oman).',
    recommendedPower: 60,
    scoutDurationSeconds: 45,
    rewards: {
      knowledge: 100,
      clay: 90,
      artifactTitle: 'Persian Gulf Button Seal & Carnelian Long-Bead',
    },
    status: 'locked',
    coordinates: { x: 32, y: 64 },
  },
  {
    id: 'ganeshwar_mines',
    title: 'Aravalli Copper Ridge',
    sanskritName: 'Aravalli Tamra Giri',
    historicalEra: 'Ganeshwar-Jodhpura Cultural Complex (c. 2800–2000 BCE)',
    terrainDescription: 'Rugged quartzite hill ranges veined with malachite and native copper ores, dotted with charcoal smelting hearths.',
    archaeologicalSite: 'Ganeshwar & Khetri Smelting Horizons',
    historicalInsight: 'Sourced and cold-hammered native copper tools, flat axes, and spearheads, supplying raw metallurgical ingots to northern urban centers.',
    recommendedPower: 75,
    scoutDurationSeconds: 50,
    rewards: {
      knowledge: 110,
      stone: 100,
      artifactTitle: 'Cast Copper Celt & Arrowhead Cluster',
    },
    status: 'locked',
    coordinates: { x: 42, y: 38 },
  },
  {
    id: 'sinauli_royal',
    title: 'Yamuna Doab Royal Necropolis',
    sanskritName: 'Sinauli Rajakiya Vyuha',
    historicalEra: 'Copper Hoard / OCP Transition (c. 2000–1800 BCE)',
    terrainDescription: 'Fertile alluvial interfluve flanked by ancient meandering oxbow lakes and timber burial chambers.',
    archaeologicalSite: 'Sinauli Excavations (ASI under D.V. Sharma)',
    historicalInsight: 'Discovered the earliest subcontinental solid-wheeled battle chariots, royal copper helmets, antenna swords, and warrior elite burials.',
    recommendedPower: 90,
    scoutDurationSeconds: 60,
    rewards: {
      knowledge: 130,
      wood: 120,
      artifactTitle: 'Copper-Inlaid Spoked Chariot Wheel',
    },
    status: 'locked',
    coordinates: { x: 48, y: 34 },
  },
  {
    id: 'bhimbetka_shelters',
    title: 'Vindhyan Stone Sanctuaries',
    sanskritName: 'Bhimbetka Shailashraya',
    historicalEra: 'Mesolithic to Historical Horizons (c. 10,000–1000 BCE)',
    terrainDescription: 'Towering weathered sandstone crags veiled in teak forest, shelter caves painted in vibrant mineral ochre.',
    archaeologicalSite: 'UNESCO World Heritage: Bhimbetka Rock Shelters',
    historicalInsight: 'Contains over 750 rock shelters spanning thousands of years, depicting communal hunts, humped bulls, wild boars, and shamanic rituals.',
    recommendedPower: 110,
    scoutDurationSeconds: 70,
    rewards: {
      knowledge: 150,
      stone: 140,
      artifactTitle: 'Ochre Painted Petroglyph of the Great Horned Beast',
    },
    status: 'locked',
    coordinates: { x: 50, y: 52 },
  },
];
