/**
 * BHARAT — Build the Civilization
 * 8-Step Progressive Onboarding & Civilization Missions
 */

import { OnboardingStep, CivilizationMission } from '../types/civilization';

export const ONBOARDING_STEPS: OnboardingStep[] = [
  {
    step: 1,
    title: 'The Sovereign Hearth',
    badge: 'Founding',
    task: 'Welcome, Sovereign Architect! Inspect your central Civilization Center (Raja Sabha) on the grand terrace.',
    hint: 'Tap on your Civilization Center in the center of the settlement to review its civic status.',
    actionButtonLabel: 'Inspect Civilization Center',
    targetTab: 'HOME',
    completed: false,
  },
  {
    step: 2,
    title: 'Gather River Resources',
    badge: 'Resources',
    task: 'Harvest seasoned timber from the North-West Grove or collect resource yields from your settlement.',
    hint: 'Tap on the Timber Yard or click "Collect Yields" to replenish building materials.',
    actionButtonLabel: 'Collect Resources',
    targetTab: 'HOME',
    completed: false,
  },
  {
    step: 3,
    title: 'Erect a Clay Workshop',
    badge: 'Construction',
    task: 'Select an open settlement plot and construct a Clay Workshop (Kumbhashala) to produce 1:2:4 terracotta bricks.',
    hint: 'Navigate to the BUILD tab or click an empty plot in your settlement.',
    actionButtonLabel: 'Open Build Menu',
    targetTab: 'BUILD',
    completed: false,
  },
  {
    step: 4,
    title: 'Reinforce the Citadel',
    badge: 'Upgrading',
    task: 'Upgrade your Civilization Center or any production structure to Level 2 to expand civic capacity.',
    hint: 'Select the Civilization Center and click "Upgrade Structure".',
    actionButtonLabel: 'Upgrade Citadel',
    targetTab: 'HOME',
    completed: false,
  },
  {
    step: 5,
    title: 'Unlock Ancient Sciences',
    badge: 'Research',
    task: 'Open the Knowledge Center (RESEARCH tab) and research your first technology: 1:2:4 Standard Fired Brick.',
    hint: 'Knowledge points are used to decode ancient engineering treatises.',
    actionButtonLabel: 'Open Research Tree',
    targetTab: 'RESEARCH',
    completed: false,
  },
  {
    step: 6,
    title: 'Guardians of the Basin',
    badge: 'Military',
    task: 'Visit the Training Ground (Akhada) in the ARMY tab and recruit a regiment of Foot Guards (Padati).',
    hint: 'Train defensive infantry to protect your granaries from roaming river raiders.',
    actionButtonLabel: 'Train Foot Guards',
    targetTab: 'ARMY',
    completed: false,
  },
  {
    step: 7,
    title: 'Civic Proclamation',
    badge: 'Missions',
    task: 'Complete a foundation mission and claim your royal knowledge reward.',
    hint: 'Review your missions list to claim completed civic achievements.',
    actionButtonLabel: 'View Missions',
    targetTab: 'HOME',
    completed: false,
  },
  {
    step: 8,
    title: 'Survey the Subcontinent',
    badge: 'Expeditions',
    task: 'Open the Regional World Map and dispatch an expedition to the Indus-Saraswati Alluvial Delta.',
    hint: 'Send scouts to discover distant archaeological ruins and new trade corridors.',
    actionButtonLabel: 'Open World Map',
    targetTab: 'MAP',
    completed: false,
  },
];

export const INITIAL_CIVILIZATION_MISSIONS: CivilizationMission[] = [
  {
    id: 'm_harvest_timber',
    title: 'Harvest the River Grove',
    sanskritTitle: 'Kashta Sangraha',
    category: 'foundation',
    description: 'Gather 100 units of seasoned wood from the riverine timber yards.',
    progress: 40,
    target: 100,
    rewardResources: {
      food: 30,
      clay: 30,
    },
    rewardXp: 40,
    rewardKnowledge: 20,
    completed: false,
    claimed: false,
  },
  {
    id: 'm_construct_structures',
    title: 'Expand Settlement Quarters',
    sanskritTitle: 'Nagara Vistara',
    category: 'production',
    description: 'Construct at least 4 functional architectural structures on settlement plots.',
    progress: 3,
    target: 4,
    rewardResources: {
      wood: 50,
      stone: 40,
    },
    rewardXp: 50,
    rewardKnowledge: 25,
    completed: false,
    claimed: false,
  },
  {
    id: 'm_upgrade_citadel',
    title: 'The Sovereign Platform',
    sanskritTitle: 'Raja Prathama',
    category: 'foundation',
    description: 'Upgrade your Civilization Center to Level 2 to expand territory and storage.',
    progress: 1,
    target: 2,
    rewardResources: {
      stone: 60,
      knowledge: 30,
    },
    rewardXp: 60,
    rewardKnowledge: 35,
    completed: false,
    claimed: false,
  },
  {
    id: 'm_research_tech',
    title: 'Wisdom of the Scribes',
    sanskritTitle: 'Vidya Abhyasa',
    category: 'research',
    description: 'Research 2 technologies in the ancient knowledge tree.',
    progress: 1,
    target: 2,
    rewardResources: {
      food: 40,
      clay: 40,
    },
    rewardXp: 50,
    rewardKnowledge: 40,
    completed: false,
    claimed: false,
  },
  {
    id: 'm_recruit_guards',
    title: 'Muster the River Garrison',
    sanskritTitle: 'Rakshaka Senani',
    category: 'military',
    description: 'Train at least 10 Padati (Foot Guards) in the martial training grounds.',
    progress: 0,
    target: 10,
    rewardResources: {
      food: 60,
      wood: 40,
    },
    rewardXp: 55,
    rewardKnowledge: 25,
    completed: false,
    claimed: false,
  },
  {
    id: 'm_scout_delta',
    title: 'Chart the Alluvial Delta',
    sanskritTitle: 'Desha Paryatana',
    category: 'discovery',
    description: 'Send a scout expedition to explore the Saraswati Delta archaeological site.',
    progress: 0,
    target: 1,
    rewardResources: {
      knowledge: 50,
      stone: 50,
    },
    rewardXp: 70,
    rewardKnowledge: 50,
    completed: false,
    claimed: false,
  },
];
