/**
 * BHARAT — Build the Civilization
 * Ancient Indian Technology & Engineering Research Tree
 */

import { TechnologyItem } from '../types/civilization';

export const TECHNOLOGIES_CATALOG: TechnologyItem[] = [
  {
    id: 'agriculture',
    name: 'Alluvial Crop Cultivation',
    sanskritName: 'Dhanya Krishi',
    era: 'early_settlements',
    category: 'agriculture',
    knowledgeCost: 20,
    prerequisites: [],
    unlocked: true, // Starting unlocked tech
    researchTimeSeconds: 5,
    effectSummary: 'Unlocks Farmland expansion and increases Granary food yields by 20%.',
    historicalContext: 'Neolithic excavations at Mehrgarh (c. 7000 BCE) reveal the earliest two-row barley and einkorn wheat domestication in the subcontinental river valleys.',
  },
  {
    id: 'brickmaking',
    name: '1:2:4 Standard Fired Brick',
    sanskritName: 'Pakva Ishtika',
    era: 'early_settlements',
    category: 'engineering',
    knowledgeCost: 35,
    prerequisites: ['agriculture'],
    unlocked: false,
    researchTimeSeconds: 15,
    effectSummary: 'Enables construction of the Clay Workshop and doubles structural durability.',
    historicalContext: 'Sun-dried and kiln-fired bricks manufactured in the precise 1:2:4 dimensional ratio allowed uniform English-bond bricklaying across thousands of square kilometers.',
    unlockedBuildingId: 'clay_workshop',
  },
  {
    id: 'hydraulic_bunds',
    name: 'Stepped Water Management',
    sanskritName: 'Jala Samrakshana',
    era: 'early_settlements',
    category: 'urban',
    knowledgeCost: 50,
    prerequisites: ['brickmaking'],
    unlocked: false,
    researchTimeSeconds: 25,
    effectSummary: 'Unlocks the Water Structure / Stepwell (Jalashaya) and increases settlement population capacity by +8.',
    historicalContext: 'Dholavira engineered sixteen interconnected rock-cut and masonry reservoirs that stored seasonal monsoon torrents to sustain a thriving desert city.',
    unlockedBuildingId: 'water_structure',
  },
  {
    id: 'stonework',
    name: 'Dressed Sandstone Masonry',
    sanskritName: 'Shila Shilpa',
    era: 'early_settlements',
    category: 'engineering',
    knowledgeCost: 45,
    prerequisites: ['brickmaking'],
    unlocked: false,
    researchTimeSeconds: 20,
    effectSummary: 'Unlocks the Stone Yard and allows Citadel upgrades past Level 2.',
    historicalContext: 'Quarry masters utilized soaked wooden wedges to cleft massive granite and sandstone monoliths for cyclopean fortification ramparts.',
    unlockedBuildingId: 'stone_yard',
  },
  {
    id: 'archery',
    name: 'Composite Bamboo Archery',
    sanskritName: 'Dhanur Vidya',
    era: 'early_settlements',
    category: 'military',
    knowledgeCost: 40,
    prerequisites: ['agriculture'],
    unlocked: false,
    researchTimeSeconds: 20,
    effectSummary: 'Unlocks the Training Ground (Akhada) and Dhanurdhara (Archer Scout) recruitment.',
    historicalContext: 'Classical Indian Dhanurveda treatises documented composite bows crafted from seasoned bamboo, sinew, and horns capable of long-range defensive volleys.',
    unlockedBuildingId: 'training_ground',
    unlockedUnitId: 'dhanurdhara',
  },
  {
    id: 'bronze_metallurgy',
    name: 'Lost-Wax Bronze Casting',
    sanskritName: 'Madhuchehishta',
    era: 'regional_crafts',
    category: 'science',
    knowledgeCost: 75,
    prerequisites: ['stonework'],
    unlocked: false,
    researchTimeSeconds: 35,
    effectSummary: 'Unlocks the Craft House (Karmashala) and forged copper chisel blanks.',
    historicalContext: 'The famous "Dancing Girl" of Mohenjo-daro stands as proof of the cire-perdue (lost-wax) metallurgy process pioneered in ancient India over 4,500 years ago.',
    unlockedBuildingId: 'craft_house',
  },
  {
    id: 'chert_weights',
    name: 'Standardized Binary & Decimal Metrics',
    sanskritName: 'Mana & Tulana',
    era: 'regional_crafts',
    category: 'science',
    knowledgeCost: 65,
    prerequisites: ['hydraulic_bunds'],
    unlocked: false,
    researchTimeSeconds: 30,
    effectSummary: 'Unlocks Market Square (Vipani) and domestic resource trading caravans.',
    historicalContext: 'Cubical chert weights followed precise ratio standards (1, 2, 4, 8, 16, 32...) that remained identical from coastal Gujarat to the northern foothills.',
    unlockedBuildingId: 'market',
  },
  {
    id: 'urban_drainage',
    name: 'Covered Sullage & Soak-Pits',
    sanskritName: 'Pranali Vyuha',
    era: 'urban_horizons',
    category: 'urban',
    knowledgeCost: 90,
    prerequisites: ['hydraulic_bunds', 'chert_weights'],
    unlocked: false,
    researchTimeSeconds: 45,
    effectSummary: 'Boosts total civilization population capacity by +25% and reduces disease risks.',
    historicalContext: 'Harappan cities pioneered the world’s first municipal sanitation systems with covered street drains, corbelled inspection manholes, and terracotta soak-jars.',
  },
  {
    id: 'caravan_routes',
    name: 'Inter-Valley Merchant Guilds',
    sanskritName: 'Sartha Yatra',
    era: 'urban_horizons',
    category: 'agriculture',
    knowledgeCost: 110,
    prerequisites: ['chert_weights'],
    unlocked: false,
    researchTimeSeconds: 50,
    effectSummary: 'Expands regional map exploration speed by 35% and increases caravan trade yield.',
    historicalContext: 'Sarthavahas (caravan leaders) guided bullock carts loaded with carnelian, lapis lazuli, shell ornaments, and fine cotton textiles across the subcontinent.',
  },
  {
    id: 'astronomical_calendars',
    name: 'Nakshatra Solar-Lunar Observatory',
    sanskritName: 'Jyotisha Kalagana',
    era: 'urban_horizons',
    category: 'science',
    knowledgeCost: 130,
    prerequisites: ['bronze_metallurgy', 'urban_drainage'],
    unlocked: false,
    researchTimeSeconds: 60,
    effectSummary: 'Generates +50 Knowledge passively per hour from celestial alignments.',
    historicalContext: 'Vedic and Harappan astronomical orientations aligned civic streets and fire altars with the cardinal points and rising constellations (Pleiades/Krittika).',
  },
];
